name: "ci"
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test

  run_action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        token: ${{secrets.GIKI_TOKEN}}
